# Calculadora
n1 = int(input("Introduce el primer número: "))
n2 = int(input("Introduce el segundo número: "))
print(f"El resultado de {n1}+{n2} es: {n1+n2}")
print(f"El resultado de {n1}-{n2} es: {n1-n2}")
print(f"El resultado de {n1}*{n2} es: {n1*n2}")
print(f"El resultado de {n1}/{n2} es: {n1/n2}")
print(f"El cociente de {n1}/{n2} es: {n1//n2}")
print(f"El resto de {n1}/{n2} es: {n1%n2}")
print(f"El resultado de {n1}^{n2} es: {n1**n2}")